repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Usa la versión más reciente o la que prefieras
    hooks:
      - id: trailing-whitespace  # Elimina espacios en blanco al final de las líneas
      - id: end-of-file-fixer    # Asegura una nueva línea al final del archivo
      - id: check-yaml           # Valida archivos YAML
      - id: check-added-large-files  # Verifica si has añadido archivos grandes
